apiVersion: v1
kind: Secret
metadata:
  name: content-core-env
type: Opaq
data:
  PARTNER_AI_CRAWLER: RmFsc2U=
  TASK_NUMBER_PER_BEAT: NDAwMA==
  RUN_XPATH_MULTI_CRAWLER: VHJ1ZQ==
  SQLALCHEMY_DATABASE_URI: cG9zdGdyZXM6Ly9wb3N0Z3JlczpDb250ZW50QnJlYWtfcHNxbDFxYXpAMzUuMjAxLjIwNy44OTo1NDMyL25ld19icmVha19jb250ZW50
  CLEAN_TABLE: RmFsc2U=
  LANG: ZW5fVVMuVVRGLTg=
  PYTHONUNBUFFERED: VHJ1ZQ==
  PYTHONIOENCODING: dXRmLTg=
  SECRET_KEY: c2VjcmV0X2tleQ==
  CELERY_TIMEZONE: QXNpYS9UYWlwZWk=
  CELERY_ACCEPT_CONTENT: anNvbg==
  CELERY_TASK_SERIALIZER: anNvbg==
  CELERY_RESULT_SERIALIZER: anNvbg==
  CELERY_DISABLED: RmFsc2U=
  SINGLE_BEAT_REDIS_SERVER: cmVkaXM6Ly8xMjcuMC4wLjE6NjM3OS80
  CELERY_BROKER_URL: cmVkaXM6Ly8xMjcuMC4wLjE6NjM3OS80
  CELERY_RESULT_BACKEND: cmVkaXM6Ly8xMjcuMC4wLjE6NjM3OS83
  CELERY_TASK_RESULT_EXPIRES: MzYwMA==
  PARTNER_SYSTEM_API: aHR0cHM6Ly9zdGctcGFydG5lci5icmVha3RpbWUuY29tLnR3L2FwaQ==
  CRAWLERA_APIKEY: ZjYzMjA5ZDY3NTY0NDIyODkxYzg2N2FiMTU4MmIwNWQ=
  PS_DOMAIN_API: aHR0cHM6Ly9zdGctcGFydG5lci5icmVha3RpbWUuY29tLnR3L2FwaS9jb25maWcv
  AC_CONTENT_STATUS_API: aHR0cDovL2FsY2hlbXkuYnJlYWt0aW1lLmNvbS50dzo4MC92MS9jb250ZW50L3N0YXR1cw==
  AC_CONTENT_MULTIPAGE_API: aHR0cDovL2FsY2hlbXkuYnJlYWt0aW1lLmNvbS50dzo4MC92MS9jb250ZW50L211bHRpX3BhZ2U=
  MERCURY_PATH: bWVyY3VyeS1wYXJzZXIvY2xpLmpz