FROM postgres:latest
MAINTAINER BreakTime Inc. <lance@breaktime.com.tw>

#WORKDIR /usr/src/app
#COPY init.sql /usr/src/app/
#RUN psql -U postgres -h localhost < /usr/src/app/init.sql
#RUN ["psql", "-U", "postgres", "-h", "localhost", "<", "/usr/src/app/init.sql"]

CMD psql -h localhost -U postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'break_content' AND pid <> pg_backend_pid()"
CMD psql -h localhost -U postgres -d break_content -c 'DROP DATABASE break_content'
CMD psql -h localhost -U postgres -d break_content -c 'CREATE DATABASE break_content'

EXPOSE 5432
COPY    entrypoint.sh /
RUN     chmod +x /entrypoint.sh
