# Pull base image.
FROM break-article-base:latest

COPY ["logging-article.sample.json", "/etc/breaktime/logging-article.json"]
COPY ["data/breaktime-article.conf", "/etc/breaktime/breaktime-article.conf"]
COPY ["data/breaktime-article-beat.conf", "/etc/breaktime/breaktime-article-beat.conf"]
COPY ["supervisor-beat.conf", "wsgi.py", "manage.py", "/opt/breaktime/"]
RUN \
  ln -s /opt/breaktime/supervisor-beat.conf /etc/supervisor/conf.d/
COPY ["./breakarticle", "/opt/breaktime/breakarticle"]
ENV SINGLE_BEAT_REDIS_SERVER redis://redis:6379/4
CMD ["supervisord", "-n"]

