version: '3.5'
services:
    redis:
        container_name: redis
        image: redis:4.0
        ports:
            - "6379:6379"
        restart: always
    nginx:
        container_name: nginx
        image: nginx:1.12
        depends_on:
            - content_core
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
    psql:
        container_name: psql
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
    content_core:
        container_name: content_core
        build:
            context: ../
            dockerfile: Dockerfile
        command: supervisord -n
        depends_on:
            - redis
        volumes:
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=content_core
        expose:
            - "8700"
        ports:
            - "8100:8100"
            - "8700:8700"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8100/v1/create_tasks/1 && echo 'OK'"]
            interval: 30m30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    pgdata:
        external: true
