version: '2'
services:
    redis:
        container_name: redis
        image: redis:4.0
        ports:
            - "6379:6379"
        restart: always
    nginx:
        container_name: nginx
        image: nginx:1.12
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
    web:
        container_name: web
        image: breaktimeinc/breaktime.contentcore
        command: /usr/local/bin/uwsgi --ini /opt/breaktime/uwsgi.ini

        volumes:
           - ../breakcontent:/opt/breaktime/breakcontent
        env_file: breakcontent.env
        expose:
            - "8700"
        ports:
            - "8700:8700"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker:
        container_name: worker
        image: breaktimeinc/breaktime.contentcore
        command: celery -A breakcontent.tasks worker -l info --autoscale=2,1 -n worker.%%h
        volumes:
           - ../breakcontent:/opt/breaktime/breakcontent
        env_file: breakcontent.env
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    beat:
        container_name: beat
        image: breaktimeinc/breaktime.contentcore
        command: single-beat celery beat -A breakcontent.tasks -l info
        volumes:
           - ../breakcontent:/opt/breaktime/breakcontent
        env_file: breakcontent.env
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
