version: '2'
services:
    worker:
        container_name: worker
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        command: celery worker -A breakcontent.tasks --loglevel=DEBUG --autoscale=300,30 -n worker.%%h -E -P gevent
        # command: celery worker -A breakcontent.tasks --loglevel=DEBUG --autoscale=300,30 -n worker -E
        # depends_on:
        #     - redis
        # command: celery worker -A breakcontent.tasks --loglevel=DEBUG --autoscale=25,8 -n worker -E
        # command: celery worker -A breakcontent.tasks --loglevel=DEBUG -n worker.%%h
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    flower:
        container_name: flower
        image: cc
        command: celery -A breakcontent.tasks flower --port=5555 --basic_auth=cc:cc
        # command: celery -A breakcontent.tasks flower --port=5555 --auth_provider=flower.views.auth.GithubLoginHandler --auth=.*
        ports:
            - "5555:5555"
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=flower
            # - FLOWER_OAUTH2_KEY=03b470c69baa3a2a67e6
            # - FLOWER_OAUTH2_SECRET=c75bb1795e31dededcdd1d2e085e0fa970d174a5
            # - FLOWER_OAUTH2_REDIRECT_URI=http://192.168.18.111:5555/login
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
