version: '2'
    worker-p1:
        container_name: worker-p1
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        command: celery worker -A breakcontent.tasks -Q priority_1 --loglevel=DEBUG --autoscale=50,1 -n worker-p1.%%h -P gevent --purge --prefetch-multiplier 4
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-p1
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-xpcrawler:
        container_name: worker-xpcrawler
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        command: celery worker -A breakcontent.tasks -Q xpcrawler --loglevel=DEBUG --autoscale=100,16 -n worker-xpcrawler.%%h --purge --prefetch-multiplier 4
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-xpcrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-xpmcrawler:
        container_name: worker-xpmcrawler
        image: cc
        command: celery worker -A breakcontent.tasks -Q xpmcrawler --loglevel=DEBUG --autoscale=40,2 -n worker-xpmcrawler.%%h -P gevent --purge --prefetch-multiplier 4
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-xpmcrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-aicrawler:
        container_name: worker-aicrawler
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        command: celery worker -A breakcontent.tasks -Q aicrawler --loglevel=DEBUG --autoscale=8,1 -n worker-aicrawler.%%h -P gevent --purge --prefetch-multiplier 4
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-aicrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
