version: '2'
services:
    redis:
        container_name: redis
        image: redis:4.0
        ports:
            - "6379:6379"
        restart: always
    beat:
        container_name: beat
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        command: single-beat celery beat -A breakcontent.tasks -l info
        # depends_on:
        #     - redis
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=beat
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker:
        container_name: worker
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        # command: celery worker -A breakcontent.tasks --loglevel=DEBUG --autoscale=20,5 -n worker.%%h -E -P gevent
        command: celery worker -A breakcontent.tasks --loglevel=DEBUG --autoscale=20,5 -n worker.%%h -E
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-xpcrawler:
        container_name: worker-xpcrawler
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        # command: celery worker -A breakcontent.tasks -Q xpcrawler --autoscale=40,10 -n worker-xpcrawler.%%h -E -P gevent
        command: celery worker -A breakcontent.tasks -Q xpcrawler --autoscale=40,10 -n worker-xpcrawler.%%h -E
        depends_on:
            - redis
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-xpcrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-xpmcrawler:
        container_name: worker-xpmcrawler
        image: cc
        # command: celery worker -A breakcontent.tasks -Q xpmcrawler --autoscale=20,4 -n worker-xpmcrawler.%%h -E -P gevent
        command: celery worker -A breakcontent.tasks -Q xpmcrawler --autoscale=20,4 -n worker-xpmcrawler.%%h -E
        depends_on:
            - redis
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-xpmcrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    worker-aicrawler:
        container_name: worker-aicrawler
        image: cc
        # image: breaktimeinc/breaktime.contentcore
        # command: celery worker -A breakcontent.tasks -Q aicrawler --autoscale=20,5 -n worker-aicrawler.%%h -E -P gevent
        command: celery worker -A breakcontent.tasks -Q aicrawler --autoscale=20,5 -n worker-aicrawler.%%h -E
        depends_on:
            - redis
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=worker-aicrawler
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
    flower:
        container_name: flower
        image: cc
        command: celery -A breakcontent.tasks flower --port=5555 --basic_auth=cc:cc
        ports:
            - "5555:5555"
        volumes:
           # - ..:/usr/src/app
           - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=flower
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always
