version: '3.5'
services:
    beat:
        container_name: beat
        image: breaktimeinc/breaktime.contentcore
        command: single-beat celery beat -A breakcontent.tasks -l info
        volumes:
            - ..:/usr/src/app
            - /var/log/contentcore:/var/log/contentcore
        env_file: breakcontent.env
        environment:
            - CONTAINER_TAG=beat
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always